const api = window.REALITY_API_BASE || `${location.protocol}//${location.hostname}:8000`;
const app = document.querySelector("#app");
const call = async (path, options = {}) => {
  const response = await fetch(`${api}${path}`, { credentials: "include", ...options });
  const data = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(data?.message || "Request failed");
  return data;
};
const layout = (title, body) => `<section><p class="eyebrow">Reality developer platform</p><h2>${title}</h2>${body}</section>`;
const renderHome = () => app.innerHTML = `<section class="hero"><p class="eyebrow">Reality Cloud · private beta</p><h1>Make 3D and CAD files programmable.</h1><p class="lede">Upload a model once. Ask deterministic geometry questions from your product, backend, or agent—without rebuilding an analysis stack.</p><div class="actions"><a class="button" href="/dashboard">Open dashboard</a><a class="button secondary" href="/docs">Read API docs</a></div></section><section class="grid"><article class="card"><h3>Reality engine</h3><p>Every query calls the open-source Reality package. No duplicated geometry logic lives in the API.</p></article><article class="card"><h3>Private by default</h3><p>Tenant-scoped IDs, hashed keys, audit logs and object storage boundaries keep models separated.</p></article><article class="card"><h3>CAD-aware</h3><p>STEP B-rep topology is preserved when the CAD adapter is installed; mesh conversion is explicitly lossy.</p></article></section>`;
const docs = () => app.innerHTML = layout("API documentation", `<p class="lede">Use a server-side API key. Do not put <code>rlt_live_</code> keys into browser JavaScript or mobile apps.</p><pre>curl ${api}/v1/files \\
  -H "Authorization: Bearer $REALITY_API_KEY" \\
  -F "file=@engine.step"</pre><p><a class="button" href="${api}/docs" target="_blank" rel="noreferrer">Open interactive OpenAPI</a></p>`);
const keys = async () => { try { const data = await call("/v1/keys"); app.innerHTML = layout("API keys", `<p class="notice">Keys are only revealed once. Copy a newly created key into a server-side secret manager.</p><form id="key-form" class="row"><label>Environment<select name="environment"><option value="test">Test</option><option value="live">Live</option></select></label><button>Create key</button></form><div id="key-result"></div><table><thead><tr><th>Prefix</th><th>Environment</th><th>Status</th><th></th></tr></thead><tbody>${data.map(k=>`<tr><td>${k.prefix}</td><td>${k.environment}</td><td>${k.status}</td><td><button class="secondary revoke" data-id="${k.id}">Revoke</button></td></tr>`).join("")}</tbody></table>`); document.querySelector("#key-form").onsubmit = async e => { e.preventDefault(); const r=await call("/v1/keys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({environment:new FormData(e.target).get("environment")})}); document.querySelector("#key-result").innerHTML=`<pre>Copy now (shown once): ${r.key}</pre>`; }; document.querySelectorAll(".revoke").forEach(b=>b.onclick=async()=>{await call(`/v1/keys/${b.dataset.id}/revoke`,{method:"POST"}); keys();}); } catch { login(); } };
const dashboard = async () => { try { const u = await call("/v1/usage"); app.innerHTML = layout("Dashboard", `<div class="grid"><article class="card"><h3>${u.stored_bytes.toLocaleString()} bytes</h3><p>of ${u.quota_bytes.toLocaleString()} storage</p></article><article class="card"><h3>${u.request_count}</h3><p>recorded API requests</p></article><article class="card"><h3>${u.keys}</h3><p>developer keys</p></article></div><div class="actions"><a class="button" href="/dashboard/keys">Manage keys</a><a class="button secondary" href="/dashboard/files">Files</a></div>`); } catch { login(); } };
function login() {
  app.innerHTML = layout("Sign in to Reality", `<form id="login"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="12" required></label><button>Sign in</button><button class="secondary" type="button" id="register">Create account</button></form>`);
  const submit = async (path) => { const f=Object.fromEntries(new FormData(document.querySelector("#login"))); await call(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)}); dashboard(); };
  document.querySelector("#login").onsubmit = async e => { e.preventDefault(); try { await submit("/v1/sessions"); } catch(error) { e.target.insertAdjacentHTML("beforeend",`<p class="error">${error.message}</p>`); } };
  document.querySelector("#register").onclick = async () => { try { await submit("/v1/accounts"); } catch(error) { document.querySelector("#login").insertAdjacentHTML("beforeend",`<p class="error">${error.message}</p>`); } };
}
function files() {
  app.innerHTML = layout("Files", `<p class="lede">Upload from this authenticated dashboard session; your API key never enters the browser.</p><form id="upload"><label>3D or CAD file<input name="file" type="file" accept=".obj,.stl,.ply,.glb,.gltf,.step,.stp" required></label><button>Upload and analyze</button></form><pre id="result">Waiting for a file.</pre>`);
  document.querySelector("#upload").onsubmit = async e => { e.preventDefault(); try { const r=await call("/v1/files",{method:"POST",body:new FormData(e.target)}); document.querySelector("#result").textContent=JSON.stringify(r,null,2); } catch(error) { document.querySelector("#result").textContent=error.message; } };
}
function playground() {
  app.innerHTML = layout("Playground", `<p class="lede">Reality makes the authoritative edit on the server. The before/after WebGL views are visual previews only.</p><form id="query"><label>Model ID<input name="id" required></label><button>Inspect summary</button></form><form id="edit"><label>Operations JSON<textarea name="operations" rows="6" required>[{"operation":"translate","parameters":{"target":"part-name","x":1.0}}]</textarea></label><button>Apply edit</button></form><div id="preview" class="grid"></div><pre id="result">No model selected.</pre>`);
  const modelId = () => new FormData(document.querySelector("#query")).get("id");
  const showPreview = (id, label) => `<article class="card"><h3>${label}</h3><model-viewer src="${api}/v1/models/${encodeURIComponent(id)}/preview" camera-controls auto-rotate alt="${label} 3D model preview"></model-viewer></article>`;
  document.querySelector("#query").onsubmit = async e => { e.preventDefault(); const id=modelId(); try { const r=await call(`/v1/models/${encodeURIComponent(id)}/summary`); document.querySelector("#result").textContent=JSON.stringify(r,null,2); document.querySelector("#preview").innerHTML=showPreview(id,"Before edit"); } catch(error) { document.querySelector("#result").textContent=error.message; } };
  document.querySelector("#edit").onsubmit = async e => { e.preventDefault(); const id=modelId(); try { const operations=JSON.parse(new FormData(e.target).get("operations")); const job=await call(`/v1/models/${encodeURIComponent(id)}/edits`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operations})}); document.querySelector("#result").textContent=JSON.stringify(job,null,2); let current=job; for(let attempts=0; attempts<50 && !["ready","failed"].includes(current.status); attempts+=1) { await new Promise(resolve=>setTimeout(resolve,250)); current=await call(`/v1/edits/${encodeURIComponent(job.id)}`); } if(current.status !== "ready" || !current.result_model_id) throw new Error(current.error || "edit did not complete"); const summary=await call(`/v1/models/${encodeURIComponent(current.result_model_id)}/summary`); document.querySelector("#result").textContent=JSON.stringify({job:current,summary},null,2); document.querySelector("#preview").innerHTML=showPreview(id,"Before edit")+showPreview(current.result_model_id,"Edited result"); } catch(error) { document.querySelector("#result").textContent=error.message; } };
}
const route = location.pathname; if (route === "/") renderHome(); else if (route === "/docs") docs(); else if (route === "/dashboard/keys") keys(); else if (route === "/dashboard/files") files(); else if (route === "/playground") playground(); else dashboard();
