from __future__ import annotations

from pathlib import Path
from xml.etree import ElementTree as ET

import pytest
import trimesh

import reality


def test_urdf_writeback_preserves_links_joint_and_recomputes_mass(tmp_path: Path) -> None:
    source = tmp_path / "arm.urdf"
    source.write_text(
        '<robot name="arm"><link name="base"><inertial><mass value="2"/>'
        '<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>'
        '</inertial><collision><geometry><box size="1 1 1"/></geometry></collision></link>'
        '<link name="tool"><collision><geometry><box size="0.2 0.2 1"/>'
        '</geometry></collision></link><joint name="shoulder" type="revolute">'
        '<parent link="base"/><child link="tool"/><origin xyz="0 0 1" rpy="0 0 0"/>'
        "</joint></robot>",
        encoding="utf-8",
    )
    obj = reality.perceive.from_3d(source, density_kg_m3=1000)
    unchanged = ET.parse(obj.export(tmp_path / "same.urdf")).getroot()
    assert unchanged.find("link/inertial/mass").get("value") == "2"
    material_only = obj.modify.material("steel").export(tmp_path / "material.urdf")
    material_root = ET.parse(material_only).getroot()
    assert material_root.find('link[@name="base"]/visual/material').get("name") == "steel"
    assert material_root.find('link[@name="base"]/inertial/mass').get("value") == "2"
    edited = obj.modify.scale(factor=2).material("steel")
    output = edited.export(tmp_path / "edited.urdf")
    root = ET.parse(output).getroot()
    assert {link.get("name") for link in root.findall("link")} == {"base", "tool"}
    assert root.find("joint").get("name") == "shoulder"
    assert float(root.find('link[@name="base"]/inertial/mass').get("value")) == pytest.approx(62800)
    assert root.find('link[@name="base"]/visual/material').get("name") == "steel"
    assert reality.perceive.from_3d(output).model is not None
    result_output = edited.result.export(tmp_path / "result.urdf")
    assert float(
        ET.parse(result_output).getroot().find('link[@name="base"]/inertial/mass').get("value")
    ) == pytest.approx(62800)


def test_generated_urdf_is_labelled_conversion(tmp_path: Path) -> None:
    path = tmp_path / "cube.obj"
    path.write_text(trimesh.creation.box().export(file_type="obj"), encoding="utf-8")
    obj = reality.perceive.from_3d(path, units="m", density_kg_m3=1000)
    output = obj.export(tmp_path / "cube.urdf")
    assert b"Generated by reality, not original" in output.read_bytes()
    assert ET.parse(output).getroot().find("link/inertial/mass") is not None


def test_generated_urdf_requires_mass_evidence(tmp_path: Path) -> None:
    path = tmp_path / "cube.obj"
    path.write_text(trimesh.creation.box().export(file_type="obj"), encoding="utf-8")
    obj = reality.perceive.from_3d(path, units="m")
    with pytest.raises(reality.PhysicsModificationError, match="density or source mass"):
        obj.export(tmp_path / "without-mass.urdf")
    assert not (tmp_path / "without-mass.urdf").exists()
