"""Audit the parallel futures milestone and write reproducible evidence."""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import time
from pathlib import Path
from typing import Any

import reality
from reality._warp_ops import evaluate_aabb_distances_cpu
from reality.predicates import collision, distance, visibility


def make_scene(object_count: int = 1_000) -> reality.World:
    box = reality.Bounds((-0.1, -0.1, -0.1), (0.1, 0.1, 0.1))
    objects = [
        reality.WorldObject("Camera", box, reality.Transform(position=(-5.0, 0.0, 0.0))),
        reality.WorldObject("Target", box, reality.Transform(position=(5.0, 0.0, 0.0))),
        reality.WorldObject("Mover", box, reality.Transform(position=(0.0, 2.0, 0.0))),
    ]
    objects.extend(
        reality.WorldObject(
            f"Static-{index}", box, reality.Transform(position=(index % 50, index // 50, 0.0))
        )
        for index in range(object_count - len(objects))
    )
    return reality.World(objects)


def git_revision() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def audit(full: bool) -> dict[str, Any]:
    world = make_scene()
    futures = world.futures(10_000).randomize_position(
        "Mover", x=(-1.0, 1.0), y=(-1.0, 1.0), z=(0.0, 0.0), seed=20260928
    )
    started = time.perf_counter()
    evaluation = futures.evaluate(
        [
            collision("Mover", "Target"),
            distance("Mover", "Target"),
            visibility("Target", from_="Camera"),
        ]
    )
    evaluation_seconds = time.perf_counter() - started
    selected = evaluation.where(collision("Mover", "Target") == False)  # noqa: E712
    cuda = reality.warp_status()
    report: dict[str, Any] = {
        "status": "PARTIAL",
        "revision": git_revision(),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "cuda": {
            "installed": cuda.installed,
            "version": cuda.version,
            "cuda_available": cuda.cuda_available,
            "devices": list(cuda.devices),
            "reason": cuda.reason,
        },
        "scene_objects": len(world.objects),
        "futures": len(futures),
        "delta_bytes": futures.delta_bytes,
        "logical_delta_bytes": len(futures) * 3 * 8,
        "evaluation_seconds": evaluation_seconds,
        "selected_without_collision": len(selected),
        "shared_snapshot": futures.shared_snapshot is world.snapshot(),
        "predicates": ["collision", "distance", "visibility"],
        "visibility_is_bounding_volume": True,
        "limitations": [
            "Local audit is CPU-only when no CUDA driver is available.",
            "Visibility uses deterministic AABB ray tests, not exact triangle-mesh rays.",
            "Batched rotation and scale are stored but predicate evaluation is not "
            "implemented yet.",
        ],
        "gpu_acceleration_next": [
            "Keep AABB centers/extents resident on GPU across many candidate batches.",
            "Move visibility ray batches and broad-phase pair culling to Warp kernels.",
            "Add GPU reduction kernels for filtering and ranking to reduce host transfers.",
        ],
    }
    if cuda.cuda_available:
        report["status"] = "PASS"
    if full:
        report["scaling"] = []
        for count in (100, 1_000, 10_000, 50_000, 100_000):
            start = time.perf_counter()
            batch = world.futures(count).randomize_position(
                "Mover", x=(-1.0, 1.0), y=(-1.0, 1.0), z=(0.0, 0.0), seed=17
            )
            creation = time.perf_counter() - start
            start = time.perf_counter()
            batch.evaluate([distance("Mover", "Target")])
            elapsed = time.perf_counter() - start
            report["scaling"].append(
                {
                    "futures": count,
                    "creation_seconds": creation,
                    "distance_seconds": elapsed,
                    "delta_bytes": batch.delta_bytes,
                }
            )
        lower = [[0.0, 0.0, 0.0], [2.0, 0.0, 0.0]]
        upper = [[1.0, 1.0, 1.0], [3.0, 1.0, 1.0]]
        report["cpu_distance_oracle"] = evaluate_aabb_distances_cpu(
            lower, upper, [[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]], [0, 1]
        ).tolist()
    return report


def markdown(report: dict[str, Any]) -> str:
    rows = report.get("scaling", [])
    scaling = (
        "\n".join(
            f"| {row['futures']} | {row['creation_seconds']:.6f} | "
            f"{row['distance_seconds']:.6f} | {row['delta_bytes']} |"
            for row in rows
        )
        or "| — | — | — | — |"
    )
    return (
        f"""# Futures audit

Status: **{report["status"]}**

This report was generated by `python tools/futures_audit.py --full --output FUTURES_AUDIT.md`.

## Reproducibility

- Revision: `{report["revision"]}`
- Python: `{report["python"]}`
- Platform: `{report["platform"]}`
- Scene objects: `{report["scene_objects"]}`
- Futures: `{report["futures"]}`
- CUDA: `{report["cuda"]["reason"]}`

## Compact state evidence

- Shared snapshot: `{report["shared_snapshot"]}`
- Measured NumPy delta bytes: `{report["delta_bytes"]}`
- Logical float64 delta payload: `{report["logical_delta_bytes"]}`
- 10k evaluation seconds: `{report["evaluation_seconds"]:.6f}`
- Candidates without collision: `{report["selected_without_collision"]}`

## Scaling

| futures | creation seconds | distance seconds | delta bytes |
|---:|---:|---:|---:|
{scaling}

## CPU/GPU boundary

Visibility is a deterministic AABB bounding-volume experiment, not exact mesh occlusion. The
custom Warp distance kernel has a CPU oracle and is validated in the CUDA test suite when a CUDA
device is present. This host reports `{report["cuda"]["reason"]}`, so the local status is
intentionally PARTIAL unless CUDA validation is available.

Future GPU work should keep immutable bounds resident, batch ray and broad-phase kernels, and
perform filtering/ranking reductions before transferring selected candidates to Python.

## Limitations

"""
        + "\n".join(f"- {item}" for item in report["limitations"])
        + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--full", action="store_true")
    parser.add_argument("--output", type=Path, default=Path("FUTURES_AUDIT.md"))
    args = parser.parse_args()
    report = audit(args.full)
    args.output.write_text(markdown(report), encoding="utf-8")
    Path("FUTURES_RESULTS.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(markdown(report))


if __name__ == "__main__":
    main()
