"""Explicit, portable scene metadata for articulations and physical properties.

Geometry formats do not agree on a standard representation for hinges, masses, or
simulation material parameters.  Reality therefore accepts a deliberately small
JSON schema rather than guessing from names or mesh topology.  The same schema can
live in glTF ``extras.reality`` or in a ``.reality.json`` sidecar.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from math import isfinite
from types import MappingProxyType

from ._models import Vector3


class SceneMetadataError(ValueError):
    """Raised when explicit Reality scene metadata is malformed or ambiguous."""


@dataclass(frozen=True, slots=True)
class ObjectMetadata:
    """Explicit configuration for one existing object name or id."""

    reference: str
    articulation: Mapping[str, object] | None = None
    physics: Mapping[str, object] | None = None

    def __post_init__(self) -> None:
        if not self.reference.strip():
            raise SceneMetadataError("metadata object reference must not be empty")
        if self.articulation is not None:
            object.__setattr__(self, "articulation", MappingProxyType(dict(self.articulation)))
        if self.physics is not None:
            object.__setattr__(self, "physics", MappingProxyType(dict(self.physics)))


@dataclass(frozen=True, slots=True)
class SceneMetadata:
    """Validated, backend-neutral import metadata.

    ``units`` follows the coordinate values in the loaded geometry.  It is a label,
    not an implicit unit conversion; automatic conversion would make mesh import
    non-deterministic without an authoritative source unit.
    """

    units: str | None = None
    objects: tuple[ObjectMetadata, ...] = ()


def parse_scene_metadata(payload: object, *, source: str) -> SceneMetadata:
    """Validate one Reality metadata document.

    Supported schema::

        {
          "units": "m",
          "objects": {
            "Door": {
              "articulation": {
                "joint": "revolute", "axis": [0, 0, 1],
                "pivot": [0, 0, 0], "limits": [0, 90]
              },
              "physics": {"mass": 12, "dynamic": true}
            }
          }
        }

    The ``articulations`` and ``physics`` list forms are accepted as convenient
    alternatives when metadata is generated by an exporter.
    """
    document = _mapping(payload, f"{source} metadata")
    if "reality" in document:
        if len(document) != 1:
            raise SceneMetadataError(f"{source}: put Reality metadata under 'reality' only")
        document = _mapping(document["reality"], f"{source}.reality")
    allowed = {"units", "objects", "articulations", "physics"}
    unknown = set(document) - allowed
    if unknown:
        names = ", ".join(sorted(str(name) for name in unknown))
        raise SceneMetadataError(f"{source}: unsupported Reality metadata fields: {names}")
    units = document.get("units")
    if units is not None and (not isinstance(units, str) or not units.strip()):
        raise SceneMetadataError(f"{source}: units must be a non-empty string")

    entries: dict[str, dict[str, Mapping[str, object]]] = {}
    objects = document.get("objects", {})
    object_map = _mapping(objects, f"{source}.objects")
    for reference, value in object_map.items():
        if not isinstance(reference, str) or not reference.strip():
            raise SceneMetadataError(f"{source}.objects keys must be non-empty strings")
        _merge_entry(entries, reference, _object_entry(value, f"{source}.objects[{reference!r}]"))
    for field in ("articulations", "physics"):
        values = document.get(field, ())
        if not isinstance(values, Sequence) or isinstance(values, str | bytes | bytearray):
            raise SceneMetadataError(f"{source}.{field} must be a list")
        singular = "articulation" if field == "articulations" else "physics"
        for index, item in enumerate(values):
            entry = _mapping(item, f"{source}.{field}[{index}]")
            object_reference = entry.get("object")
            if not isinstance(object_reference, str) or not object_reference.strip():
                raise SceneMetadataError(
                    f"{source}.{field}[{index}].object must be a non-empty string"
                )
            config = {key: value for key, value in entry.items() if key != "object"}
            _merge_entry(
                entries,
                object_reference,
                {singular: _validate_config(singular, config, source)},
            )
    return SceneMetadata(
        units=units.strip() if isinstance(units, str) else None,
        objects=tuple(
            ObjectMetadata(
                reference=reference,
                articulation=config.get("articulation"),
                physics=config.get("physics"),
            )
            for reference, config in entries.items()
        ),
    )


def merge_scene_metadata(*documents: SceneMetadata) -> SceneMetadata:
    """Merge metadata in precedence order, with later documents overriding fields."""
    units: str | None = None
    entries: dict[str, dict[str, Mapping[str, object]]] = {}
    for document in documents:
        if document.units is not None:
            units = document.units
        for item in document.objects:
            next_entry: dict[str, Mapping[str, object]] = {}
            if item.articulation is not None:
                next_entry["articulation"] = item.articulation
            if item.physics is not None:
                next_entry["physics"] = item.physics
            _merge_entry(entries, item.reference, next_entry)
    return SceneMetadata(
        units=units,
        objects=tuple(
            ObjectMetadata(
                reference=reference,
                articulation=config.get("articulation"),
                physics=config.get("physics"),
            )
            for reference, config in entries.items()
        ),
    )


def _merge_entry(
    entries: dict[str, dict[str, Mapping[str, object]]],
    reference: str,
    entry: Mapping[str, Mapping[str, object]],
) -> None:
    entries.setdefault(reference, {}).update(entry)


def _object_entry(value: object, source: str) -> dict[str, Mapping[str, object]]:
    entry = _mapping(value, source)
    allowed = {"articulation", "physics"}
    unknown = set(entry) - allowed
    if unknown:
        names = ", ".join(sorted(str(name) for name in unknown))
        raise SceneMetadataError(f"{source}: unsupported object metadata fields: {names}")
    result: dict[str, Mapping[str, object]] = {}
    for field in allowed:
        if field in entry:
            result[field] = _validate_config(field, entry[field], source)
    return result


def _validate_config(field: str, value: object, source: str) -> Mapping[str, object]:
    config = _mapping(value, f"{source}.{field}")
    if field == "articulation":
        allowed = {
            "joint",
            "axis",
            "limits",
            "pivot",
            "current",
            "angular_resolution",
            "linear_resolution",
        }
        required = {"joint", "axis", "limits"}
        missing = required - set(config)
        if missing:
            raise SceneMetadataError(f"{source}.articulation missing: {', '.join(sorted(missing))}")
        unknown = set(config) - allowed
        if unknown:
            raise SceneMetadataError(f"{source}.articulation has unsupported fields: {unknown}")
        joint = config["joint"]
        if joint not in {"revolute", "prismatic"}:
            raise SceneMetadataError(
                f"{source}.articulation.joint must be 'revolute' or 'prismatic'"
            )
        validated: dict[str, object] = {
            "joint": joint,
            "axis": _vector(config["axis"], f"{source}.articulation.axis"),
            "limits": _limits(config["limits"], f"{source}.articulation.limits"),
        }
        if "pivot" in config:
            validated["pivot"] = _vector(config["pivot"], f"{source}.articulation.pivot")
        for name in ("current", "angular_resolution", "linear_resolution"):
            if name in config:
                validated[name] = _number(config[name], f"{source}.articulation.{name}")
        return MappingProxyType(validated)
    allowed = {"mass", "dynamic", "collision_shape", "friction", "restitution", "center_of_mass"}
    unknown = set(config) - allowed
    if unknown:
        raise SceneMetadataError(f"{source}.physics has unsupported fields: {unknown}")
    validated = {}
    for name in ("mass", "friction", "restitution"):
        if name in config:
            validated[name] = _number(config[name], f"{source}.physics.{name}")
    if "dynamic" in config:
        if not isinstance(config["dynamic"], bool):
            raise SceneMetadataError(f"{source}.physics.dynamic must be a boolean")
        validated["dynamic"] = config["dynamic"]
    if "collision_shape" in config:
        if config["collision_shape"] != "box":
            raise SceneMetadataError(f"{source}.physics.collision_shape must be 'box'")
        validated["collision_shape"] = "box"
    if "center_of_mass" in config:
        validated["center_of_mass"] = _vector(
            config["center_of_mass"], f"{source}.physics.center_of_mass"
        )
    return MappingProxyType(validated)


def _mapping(value: object, source: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        raise SceneMetadataError(f"{source} must be an object")
    if not all(isinstance(key, str) for key in value):
        raise SceneMetadataError(f"{source} keys must be strings")
    return value


def _number(value: object, source: str) -> float:
    if isinstance(value, bool) or not isinstance(value, int | float) or not isfinite(float(value)):
        raise SceneMetadataError(f"{source} must be a finite number")
    return float(value)


def _vector(value: object, source: str) -> Vector3:
    if (
        not isinstance(value, Sequence)
        or isinstance(value, str | bytes | bytearray)
        or len(value) != 3
    ):
        raise SceneMetadataError(f"{source} must contain exactly three finite numbers")
    return tuple(_number(item, source) for item in value)  # type: ignore[return-value]


def _limits(value: object, source: str) -> tuple[float, float]:
    if (
        not isinstance(value, Sequence)
        or isinstance(value, str | bytes | bytearray)
        or len(value) != 2
    ):
        raise SceneMetadataError(f"{source} must contain exactly two finite numbers")
    return _number(value[0], source), _number(value[1], source)
