"""Interchange helpers; visuals are never treated as authoritative physics."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING
from xml.etree import ElementTree as ET

import numpy as np
import trimesh
from numpy.typing import NDArray

from ._physics_modify import PhysicsModificationError, _world_mesh

if TYPE_CHECKING:
    from ._physics_object import PhysicsObject

_METRES = {"m": 1.0, "mm": 0.001, "cm": 0.01, "um": 0.000001, "in": 0.0254, "ft": 0.3048}


def _vector(values: NDArray[np.float64]) -> str:
    return "Vector3(" + ", ".join(format(float(value), ".12g") for value in values) + ")"


def export_godot(obj: PhysicsObject, target: Path) -> Path:
    """Write a Godot 4 scene with AABB collision and imported GLB visual instances.

    Godot imports GLB as ``PackedScene``. That scene contains MeshInstance3D
    children, so assigning the GLB directly to a MeshInstance3D ``mesh`` field
    would be a type error. One per-part GLB is instanced under each rigid body.
    """
    if target.suffix.lower() != ".tscn":
        raise PhysicsModificationError("Godot scene export requires a .tscn path")
    if obj.units not in _METRES:
        raise PhysicsModificationError("Godot export requires known length units")
    if any(part._mesh is None or part.solid is not None for part in obj.parts):
        raise PhysicsModificationError("Godot mesh export cannot preserve CAD B-rep")
    scale = _METRES[obj.units]
    target.parent.mkdir(parents=True, exist_ok=True)
    resources: list[str] = []
    nodes = ['[node name="RealityScene" type="Node3D"]']
    for index, part in enumerate(obj.parts, 1):
        mesh = _world_mesh(part)
        mesh.apply_scale(scale)
        sidecar = target.with_name(
            f"{target.stem}_mesh.glb" if len(obj.parts) == 1 else f"{target.stem}_mesh_{index}.glb"
        )
        scene = trimesh.Scene()
        scene.add_geometry(mesh, node_name=part.name, geom_name=part.name)
        sidecar.write_bytes(scene.export(file_type="glb"))
        resource_id = f"visual_{index}"
        box_id = f"box_{index}"
        material_id = f"physics_{index}"
        resources.append(
            f'[ext_resource type="PackedScene" path={json.dumps(sidecar.name)} id="{resource_id}"]'
        )
        resources.append(
            f'[sub_resource type="BoxShape3D" id="{box_id}"]\n'
            f"size = {_vector(np.asarray(mesh.extents))}"
        )
        resources.append(
            f'[sub_resource type="PhysicsMaterial" id="{material_id}"]\n'
            "friction = 0.5\nbounce = 0.0"
        )
        mass = (
            float(part.volume * scale**3 * obj.density_kg_m3)
            if part.volume is not None and obj.density_kg_m3 is not None
            else float(obj.estimated_mass)
            if len(obj.parts) == 1 and obj.estimated_mass is not None
            else 1.0
        )
        if mass <= 0:
            mass = 1.0
        body = f"Part_{index}"
        nodes.extend(
            [
                f'[node name="{body}" type="RigidBody3D" parent="."]\n'
                f"mass = {format(mass, '.12g')}\n"
                f'physics_material_override = SubResource("{material_id}")',
                f'[node name="CollisionShape3D" type="CollisionShape3D" parent="{body}"]\n'
                f'shape = SubResource("{box_id}")\n'
                f"position = {_vector(np.asarray(mesh.bounds).mean(axis=0))}",
                f'[node name="Visual" parent="{body}" instance=ExtResource("{resource_id}")]',
            ]
        )
    text = (
        f"[gd_scene load_steps={1 + 3 * len(obj.parts)} format=3]\n\n"
        + "\n\n".join(resources)
        + "\n\n"
        + "\n\n".join(nodes)
        + "\n"
    )
    target.write_text(text, encoding="utf-8")
    return target


def export_ros2(obj: PhysicsObject, target: Path, urdf: str) -> Path:
    """Write a ROS 2 node template; package registration remains the user's job."""
    if target.suffix.lower() != ".py":
        raise PhysicsModificationError("ROS 2 helper requires a .py path")
    robot_root = ET.fromstring(urdf)
    joint_names = [
        name
        for joint in robot_root.findall("joint")
        if joint.get("type") != "fixed" and (name := joint.get("name"))
    ]
    mobile = any(
        part.metadata.get("source_link") == "base_link" or part.name == "base_link"
        for part in obj.parts
    )
    script = (
        "# Generated by reality\n"
        "# Requires: ros2, rclpy\n"
        "# Run: ros2 run <your_package> robot_node (after registering an entry point)\n"
        "# This node publishes descriptions/states; it does not command actuators.\n"
        "import rclpy\n"
        "from rclpy.node import Node\n"
        "from rclpy.qos import QoSProfile, DurabilityPolicy\n"
        "from std_msgs.msg import String\n"
        "from sensor_msgs.msg import JointState\n"
        "from geometry_msgs.msg import Twist\n\n"
        f"ROBOT_DESCRIPTION = {urdf!r}\n"
        f"JOINT_NAMES = {joint_names!r}\n\n"
        "class RealityRobotNode(Node):\n"
        "    def __init__(self):\n"
        "        super().__init__('reality_robot')\n"
        "        qos = QoSProfile(depth=1, durability=DurabilityPolicy.TRANSIENT_LOCAL)\n"
        "        self.description_pub = self.create_publisher(String, 'robot_description', qos)\n"
        "        self.joint_pub = self.create_publisher(JointState, '/joint_states', 10)\n"
        "        self.description_pub.publish(String(data=ROBOT_DESCRIPTION))\n"
        "        self.create_timer(0.1, self.publish_joint_states)\n"
    )
    if mobile:
        script += (
            "        self.create_subscription(Twist, '/cmd_vel', self.on_velocity, 10)\n\n"
            "    def on_velocity(self, message):\n"
            "        # Application-specific actuator integration belongs here.\n"
            "        self.get_logger().debug(f'cmd_vel linear={message.linear.x}')\n\n"
        )
    else:
        script += "\n"
    script += (
        "    def publish_joint_states(self):\n"
        "        state = JointState()\n"
        "        state.header.stamp = self.get_clock().now().to_msg()\n"
        "        state.name = JOINT_NAMES\n"
        "        state.position = [0.0] * len(JOINT_NAMES)\n"
        "        self.joint_pub.publish(state)\n\n"
        "def main(args=None):\n"
        "    rclpy.init(args=args)\n"
        "    node = RealityRobotNode()\n"
        "    try:\n"
        "        rclpy.spin(node)\n"
        "    finally:\n"
        "        node.destroy_node()\n"
        "        rclpy.shutdown()\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    return target
